=== FlyingFree-P4/PaginaWeb/PaginaProva/xml/hotels.dtd
<!ELEMENT hotels (hotel)+>
<!ELEMENT hotel (nom,desti,descripcio,persones,dia,hora,preu)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT desti (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT persones (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT preu (#PCDATA)>


<!ATTLIST hotel id CDATA #REQUIRED>

=== FlyingFree-P4/PaginaWeb/PaginaProva/xml/hotels.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hotels SYSTEM "hotels.dtd">

<hotels>
  <hotel id="hotel1">
    <nom>Arts</nom>
    <desti>Barcelona, Espanya</desti>
    <descripcio>Millor hotel a la costa amb dos cames dobles</descripcio>
    <persones>4</persones>
    <dia>15/10/2021</dia>
    <hora>10:00</hora>
    <preu>232</preu>
  </hotel>
<hotel id="hotel2">
    <nom>Four Seasons</nom>
    <desti>Moscow, Rusia</desti>
    <descripcio>Millor hotel del centre de la ciutat amb cama doble i piscina propia</descripcio>
    <persones>2</persones>
    <dia>15/10/2021</dia>
    <hora>10:30</hora>
    <preu>421</preu>
  </hotel>
  <hotel id="hotel3">
    <nom>The Mark</nom>
    <desti>New York, USA</desti>
    <descripcio>Millor hotel del centre de la ciutat amb una cama doble i dos individuals</descripcio>
    <persones>4</persones>
    <dia>15/10/2021</dia>
    <hora>12:00</hora>
    <preu>630</preu>
  </hotel>
  <hotel id="hotel4">
    <nom>Burj al-Arab</nom>
    <desti>Dubai, Emirates Arabes Unidos</desti>
    <descripcio>Millor hotel a la costa amb una cama doble i dos individuals, jacusi en la habitacio</descripcio>
    <persones>4</persones>
    <dia>15/10/2021</dia>
    <hora>10:25</hora>
    <preu>1297</preu>
  </hotel>
</hotels>
