=== FlyingFree-P4/PaginaWeb/xml/excursions.dtd
<!ELEMENT sortides (excursions*)>
<!ELEMENT excursions (nom, desti, imatge, descripcio, persones, dia, hora, preu)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT desti (#PCDATA)>
<!ELEMENT imatge (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT persones (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT preu (#PCDATA)>


<!ATTLIST excursions id ID #REQUIRED>

=== FlyingFree-P4/PaginaWeb/PaginaProva/xml/excursions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sortides SYSTEM "excursions.dtd"> 
<sortides>
  <excursions id="excur1">
    <nom>Ferrari World</nom>
    <desti>Abu Dhabi</desti>
    <imatge>#</imatge>
    <descripcio>Millor excurcio en Dubai</descripcio>
    <persones>4</persones>
    <dia>15/10/2021</dia>
    <hora>09:00</hora>
    <preu>150</preu>
  </excursions>
  <excursions id="excur2">
    <nom>Port Aventura</nom>
    <desti>Salou</desti>
    <imatge>#</imatge>
    <descripcio>Millor excurcio en Barcelona</descripcio>
    <persones>2</persones>
    <dia>16/11/2021</dia>
    <hora>10:00</hora>
    <preu>80</preu>
  </excursions>

</sortides>
